### ISSUE TITLE
CPU profile can produce invalid JSON with Regex function names

### ISSUE THREAD

**Issue by robross0606** [nodesource/nsolid#178]
When producing a CPU Profile where something like this is declared in the code:

![image](https://github.com/user-attachments/assets/28061585-5e10-48da-b081-0f1682a99154)

The CPU profile is created, but not viewable in N|Solid console.  It just hangs on this page forever:
![image](https://github.com/user-attachments/assets/9c1b428f-910c-4b6e-8a31-42ac7b3c7a64)

Downloading and examining the profile as JSON, we can see the results are corrupted/invalid JSON because it does not properly escape Regex function names:
![image](https://github.com/user-attachments/assets/abe4508c-3e6c-4f4e-b836-a233d5efb951)
That should be this:
![image](https://github.com/user-attachments/assets/98a67373-c13e-49d3-b41f-b189c97a442e)

Neither N|Solid, nor Chrome Dev Tools nor VSCode, nor any other profile analysis tool can parse the file as generated by N|Solid.

**Comment by santigimeno** [comment]
@robross0606 thanks for the report. I think we have a fix but couldn't reproduce the actual issue even by using your Regex. Could you provide a full reproducer? Thanks
